In [4]:
import numpy as np
import pandas as pd
import math
from sklearn import linear_model


In [10]:
df = pd.read_excel("Onehot_encod.xlsx")
df.columns
df     

Town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [13]:
# creating the dummy variables for the column town.
dummies = pd.get_dummies(df.Town)
dummies


monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [116]:
# now we will ocncatinate the dummies data frame with the original data-frame

merged = pd.concat([df, dummies], axis = 'columns')
merged.columns
merged


Town  area   price  monroe township  robinsville  west windsor
0      0  2600  550000             True        False         False
1      0  3000  565000             True        False         False
2      0  3200  610000             True        False         False
3      0  3600  680000             True        False         False
4      0  4000  725000             True        False         False
5      2  2600  585000            False        False          True
6      2  2800  615000            False        False          True
7      2  3300  650000            False        False          True
8      2  3600  710000            False        False          True
9      1  2600  575000            False         True         False
10     1  2900  600000            False         True         False
11     1  3100  620000            False         True         False
12     1  3600  695000            False         True         False

In [15]:
# if we want to concatinate the data column wise then we will provide the axis = columns.
# once we have created the dummy variables we will drop the town column and even if we will not drop the one 
# dummy column then also linear regression understand about the dummy variable trap and it will automatically
# know about it.



df_1 = merged.drop(["Town", "monroe township"], axis = 'columns')
# df_1[['robinsville','west windsor']].astype(int)
df_2 = df_1[['robinsville', 'west windsor']].astype(int)
df_2
df_3 = df_1.drop(['robinsville','west windsor'], axis = 'columns')
df_3
df_4 = pd.concat([df_3, df_2], axis = 'columns')

df_4


area   price  robinsville  west windsor
0   2600  550000            0             0
1   3000  565000            0             0
2   3200  610000            0             0
3   3600  680000            0             0
4   4000  725000            0             0
5   2600  585000            0             1
6   2800  615000            0             1
7   3300  650000            0             1
8   3600  710000            0             1
9   2600  575000            1             0
10  2900  600000            1             0
11  3100  620000            1             0
12  3600  695000            1             0

In [18]:
# now as you can see above we have converted all the boolean values in the integers
# the data frame that we have received now is the perfect data frame for us. 


# Extracting x. 


In [17]:
x = df_4.drop(['price'], axis = 'columns')
x

area  robinsville  west windsor
0   2600            0             0
1   3000            0             0
2   3200            0             0
3   3600            0             0
4   4000            0             0
5   2600            0             1
6   2800            0             1
7   3300            0             1
8   3600            0             1
9   2600            1             0
10  2900            1             0
11  3100            1             0
12  3600            1             0

# Extracting the Y

In [19]:
y = df_1.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [20]:
model = linear_model.LinearRegression()
model


LinearRegression()

# training the model 


In [21]:

model.fit(x,y) # to avoide the training again and again we can save this model in pickle file.


LinearRegression()

In [22]:
model.predict([[3400, 0,1]])

/Users/pavankumar/.pyenv/versions/3.8.10/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.6684584])

# Chek the accuracy of your model by providing x & y values 

In [23]:
model.score(x,y)

0.9573929037221872

# Now we will use one-hot encodign to do the same thing 
# Using sklearn OneHotEncoder

In [ ]:
# To use the one hot encoding first we need to use the label encoding in the town column. 
# Because town column only has the words instead of numbers.


# imorting the label encoder 

In [24]:
df

Town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()




# The below data is with label encoding column.

In [49]:
dfle = df
dfle['Town'] = le.fit_transform(dfle['Town'])
dfle



Town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

# Now we will transform our data with one hot encoding vectors 

In [134]:
X = dfle[['Town','area']].values
X


array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [135]:
Y = dfle.price
Y



0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

Importing one hot encoder to convert the data in to one hot encoder vactor 


In [136]:
from sklearn.preprocessing import OneHotEncoder 
# ohe = OneHotEncoder(categorical_features =[0])
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Assuming you have a DataFrame called 'df' with a 'Town' column to encode
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough')

df_encoded_X = ct.fit_transform(X)
df_encoded_X


array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [137]:
# now the above data in array df_encoded_X to avoide the dummy variable trap we will drop one column of one hot 
# encoder 

# to drop a column in array we follw different approach than in data frame

X_ready = df_encoded_X[:,1:]
X_ready

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [139]:
Y_ready = Y





In [127]:
One_hot_encoded_model = model.fit(X_ready, Y_ready)
One_hot_encoded_model.coef_
One_hot_encoded_model.intercept_
One_hot_encoded_model.score(X_ready, Y_ready)





0.9573929037221872

In [128]:
# 3400 area price in westwinser as westsinser = 2 as given in X values

One_hot_encoded_model.predict([[0,1,3400]]) 






array([681241.6684584])